### ISSUE TITLE
AttributeError: 'AxisLimits' object has no attribute 'populateDefaults'

### ISSUE THREAD

**Issue by LYS1THEA** [moi15moi/FontCollector#20] opened 2023-03-24 18:47 UTC
```cmd
fontcollector -i "01.ass"
ERROR - An unknown error occurred while reading the font "C:\Windows\Fonts\bahnschrift.ttf"
Please open an issue on github, share the font and the following error message:
Traceback (most recent call last):
  File "C:\Users\leah\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\leah\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\leah\.local\bin\fontcollector.exe\__main__.py", line 7, in <module>
  File "C:\Users\leah\.local\pipx\venvs\fontcollector\lib\site-packages\font_collector\__main__.py", line 26, in main
    font_collection = FontLoader(additional_fonts, use_system_font).fonts
  File "C:\Users\leah\.local\pipx\venvs\fontcollector\lib\site-packages\font_collector\font_loader.py", line 25, in __init__
    self.system_fonts = FontLoader.load_system_fonts()
  File "C:\Users\leah\.local\pipx\venvs\fontcollector\lib\site-packages\font_collector\font_loader.py", line 97, in load_system_fonts
    system_fonts.update(Font.from_font_path(font_path))
  File "C:\Users\leah\.local\pipx\venvs\fontcollector\lib\site-packages\font_collector\font.py", line 76, in from_font_path
    axis_value_tables = FontParser.get_axis_value_from_coordinates(
  File "C:\Users\leah\.local\pipx\venvs\fontcollector\lib\site-packages\font_collector\font_parser.py", line 157, in get_axis_value_from_coordinates
    axisLimits = AxisLimits(coordinates).populateDefaults(font)
AttributeError: 'AxisLimits' object has no attribute 'populateDefaults'
```

**Comment by moi15moi** [comment] 2023-03-24 19:35
This is cause by the last version of fonttools. 4.39.X

This PR #19 correct this problem, but I still need to test it properly.

**Comment by moi15moi** [comment] 2023-03-27 01:13
@LYS1THEA Could you confirm me that you don't have anymore problem with the last version?

To update it, use this command:
```
pip install FontCollector -U
```

**Comment by moi15moi** [comment] 2023-03-27 10:08
Could you give me all the font that is been loaded?
See the font mentionned above the crash error.

You seems to have a broken font and fonttools doesn't like it.
Sorry for the inconvenience

**Comment by moi15moi** [comment] 2023-03-27 13:20
I found your font online.
This issue is caused by fonttools. Currently, there is nothing I can do to correct this behaviour.

I opened an issue on their github: https://github.com/fonttools/fonttools/issues/3060

**Comment by moi15moi** [comment] 2023-04-08 15:55
I will close this issue since the original issue have been resolved.

The "new" issue is caused by fonttools which isn't what this repos is about.

**Closed by moi15moi** 2023-04-08 15:55 UTC
